// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/posts/posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_proto_posts_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Post) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AddPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostRequest) Reset() {
	*x = AddPostRequest{}
	mi := &file_proto_posts_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostRequest) ProtoMessage() {}

func (x *AddPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostRequest.ProtoReflect.Descriptor instead.
func (*AddPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{1}
}

func (x *AddPostRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AddPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPostResponse) Reset() {
	*x = AddPostResponse{}
	mi := &file_proto_posts_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPostResponse) ProtoMessage() {}

func (x *AddPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPostResponse.ProtoReflect.Descriptor instead.
func (*AddPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{2}
}

func (x *AddPostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_proto_posts_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePostRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"` // optional, depending on whether you want to return the deleted post
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostResponse) Reset() {
	*x = DeletePostResponse{}
	mi := &file_proto_posts_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostResponse) ProtoMessage() {}

func (x *DeletePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostResponse.ProtoReflect.Descriptor instead.
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePostResponse) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_proto_posts_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{5}
}

type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_proto_posts_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{6}
}

func (x *GetFeedResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type VKAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKAuthRequest) Reset() {
	*x = VKAuthRequest{}
	mi := &file_proto_posts_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKAuthRequest) ProtoMessage() {}

func (x *VKAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKAuthRequest.ProtoReflect.Descriptor instead.
func (*VKAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{7}
}

func (x *VKAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VKAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VKAuthResponse) Reset() {
	*x = VKAuthResponse{}
	mi := &file_proto_posts_posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VKAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VKAuthResponse) ProtoMessage() {}

func (x *VKAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VKAuthResponse.ProtoReflect.Descriptor instead.
func (*VKAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{8}
}

func (x *VKAuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VKAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetVKAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKAuthURLRequest) Reset() {
	*x = GetVKAuthURLRequest{}
	mi := &file_proto_posts_posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKAuthURLRequest) ProtoMessage() {}

func (x *GetVKAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetVKAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{9}
}

type GetVKAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVKAuthURLResponse) Reset() {
	*x = GetVKAuthURLResponse{}
	mi := &file_proto_posts_posts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVKAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVKAuthURLResponse) ProtoMessage() {}

func (x *GetVKAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_posts_posts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVKAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetVKAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_posts_posts_proto_rawDescGZIP(), []int{10}
}

func (x *GetVKAuthURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_posts_posts_proto protoreflect.FileDescriptor

const file_proto_posts_posts_proto_rawDesc = "" +
	"\n" +
	"\x17proto/posts/posts.proto\x12\tsocialnet\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\"$\n" +
	"\x0eAddPostRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"6\n" +
	"\x0fAddPostResponse\x12#\n" +
	"\x04post\x18\x01 \x01(\v2\x0f.socialnet.PostR\x04post\"#\n" +
	"\x11DeletePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x12DeletePostResponse\x12#\n" +
	"\x04post\x18\x01 \x01(\v2\x0f.socialnet.PostR\x04post\"\x10\n" +
	"\x0eGetFeedRequest\"8\n" +
	"\x0fGetFeedResponse\x12%\n" +
	"\x05posts\x18\x01 \x03(\v2\x0f.socialnet.PostR\x05posts\"#\n" +
	"\rVKAuthRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"?\n" +
	"\x0eVKAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x15\n" +
	"\x13GetVKAuthURLRequest\"(\n" +
	"\x14GetVKAuthURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xdc\x01\n" +
	"\vPostService\x12@\n" +
	"\aAddPost\x12\x19.socialnet.AddPostRequest\x1a\x1a.socialnet.AddPostResponse\x12I\n" +
	"\n" +
	"DeletePost\x12\x1c.socialnet.DeletePostRequest\x1a\x1d.socialnet.DeletePostResponse\x12@\n" +
	"\aGetFeed\x12\x19.socialnet.GetFeedRequest\x1a\x1a.socialnet.GetFeedResponse2\x9d\x01\n" +
	"\vAuthService\x12=\n" +
	"\x06VKAuth\x12\x18.socialnet.VKAuthRequest\x1a\x19.socialnet.VKAuthResponse\x12O\n" +
	"\fGetVKAuthURL\x12\x1e.socialnet.GetVKAuthURLRequest\x1a\x1f.socialnet.GetVKAuthURLResponseB\x17Z\x15socialnet/proto/postsb\x06proto3"

var (
	file_proto_posts_posts_proto_rawDescOnce sync.Once
	file_proto_posts_posts_proto_rawDescData []byte
)

func file_proto_posts_posts_proto_rawDescGZIP() []byte {
	file_proto_posts_posts_proto_rawDescOnce.Do(func() {
		file_proto_posts_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_posts_posts_proto_rawDesc), len(file_proto_posts_posts_proto_rawDesc)))
	})
	return file_proto_posts_posts_proto_rawDescData
}

var file_proto_posts_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_posts_posts_proto_goTypes = []any{
	(*Post)(nil),                  // 0: socialnet.Post
	(*AddPostRequest)(nil),        // 1: socialnet.AddPostRequest
	(*AddPostResponse)(nil),       // 2: socialnet.AddPostResponse
	(*DeletePostRequest)(nil),     // 3: socialnet.DeletePostRequest
	(*DeletePostResponse)(nil),    // 4: socialnet.DeletePostResponse
	(*GetFeedRequest)(nil),        // 5: socialnet.GetFeedRequest
	(*GetFeedResponse)(nil),       // 6: socialnet.GetFeedResponse
	(*VKAuthRequest)(nil),         // 7: socialnet.VKAuthRequest
	(*VKAuthResponse)(nil),        // 8: socialnet.VKAuthResponse
	(*GetVKAuthURLRequest)(nil),   // 9: socialnet.GetVKAuthURLRequest
	(*GetVKAuthURLResponse)(nil),  // 10: socialnet.GetVKAuthURLResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_posts_posts_proto_depIdxs = []int32{
	11, // 0: socialnet.Post.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: socialnet.AddPostResponse.post:type_name -> socialnet.Post
	0,  // 2: socialnet.DeletePostResponse.post:type_name -> socialnet.Post
	0,  // 3: socialnet.GetFeedResponse.posts:type_name -> socialnet.Post
	1,  // 4: socialnet.PostService.AddPost:input_type -> socialnet.AddPostRequest
	3,  // 5: socialnet.PostService.DeletePost:input_type -> socialnet.DeletePostRequest
	5,  // 6: socialnet.PostService.GetFeed:input_type -> socialnet.GetFeedRequest
	7,  // 7: socialnet.AuthService.VKAuth:input_type -> socialnet.VKAuthRequest
	9,  // 8: socialnet.AuthService.GetVKAuthURL:input_type -> socialnet.GetVKAuthURLRequest
	2,  // 9: socialnet.PostService.AddPost:output_type -> socialnet.AddPostResponse
	4,  // 10: socialnet.PostService.DeletePost:output_type -> socialnet.DeletePostResponse
	6,  // 11: socialnet.PostService.GetFeed:output_type -> socialnet.GetFeedResponse
	8,  // 12: socialnet.AuthService.VKAuth:output_type -> socialnet.VKAuthResponse
	10, // 13: socialnet.AuthService.GetVKAuthURL:output_type -> socialnet.GetVKAuthURLResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_posts_posts_proto_init() }
func file_proto_posts_posts_proto_init() {
	if File_proto_posts_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_posts_posts_proto_rawDesc), len(file_proto_posts_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_posts_posts_proto_goTypes,
		DependencyIndexes: file_proto_posts_posts_proto_depIdxs,
		MessageInfos:      file_proto_posts_posts_proto_msgTypes,
	}.Build()
	File_proto_posts_posts_proto = out.File
	file_proto_posts_posts_proto_goTypes = nil
	file_proto_posts_posts_proto_depIdxs = nil
}
